---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation
# all, none, or list of linter keys

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
ENABLE:
  - ACTION
  - BASH
  - CSS
  - DOCKERFILE
  - EDITORCONFIG
  - GO
  - HTML
  - JAVASCRIPT
  - JSON
  - MAKEFILE
  - MARKDOWN
  - REPOSITORY
  - YAML

DISABLE_LINTERS:
  - HTML_HTMLHINT # HTMLHint was disabled as HTMLHint doesn't understand GoLang syntax so there was a lot of false positives

FORMATTERS_DISABLE_ERRORS: false # Ensures code is actually fixable when using `make megalint-apply`
SHOW_ELAPSED_TIME: true # Displays execution time for each linter
FLAVOR_SUGGESTIONS: false # Disables suggestions to use different MegaLinter flavors
PARALLEL_PROCESS_NUMBER: 1
FILTER_REGEX_EXCLUDE: (megalinter-reports/.*)
GO_GOLANGCI_LINT_ARGUMENTS: ["-c", ".golangci.yml"]
GO_REVIVE_ARGUMENTS: ["-config", "revive.toml"]
REPOSITORY_KINGFISHER_ARGUMENTS: ["--exclude", "jwt-test-keys/**"]

ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN

HTML_DJLINT_ARGUMENTS: ["--profile", "golang"]
