ignoreGeneratedHeader = true
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.increment-decrement]
[rule.range]
[rule.receiver-naming]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.waitgroup-by-value]
[rule.exported]
[rule.package-comments]
[rule.var-naming]
[rule.redefines-builtin-id]
[rule.unused-parameter]
