apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: census31-eq-questionnaire-launcher
build:
  artifacts:
    - image: launcher-image
manifests:
  rawYaml:
    - deploy/service.yaml
deploy:
  cloudrun: {}