---
steps:
  - name: gcr.io/cloud-builders/docker
    id: docker-build-eq-launcher
    args:
      - buildx
      - build
      - "--platform=${_PLATFORM}"
      - "--load"
      - "-t"
      - "europe-west2-docker.pkg.dev/${_PROJECT_ID}/census31-eq-questionnaire-launcher/launcher:${SHORT_SHA}"
      - "."

  # Push Docker image to GAR
  - name: gcr.io/cloud-builders/docker
    id: docker-push
    args:
      - push
      - "europe-west2-docker.pkg.dev/${_PROJECT_ID}/census31-eq-questionnaire-launcher/launcher:${SHORT_SHA}"

images:
  - "europe-west2-docker.pkg.dev/${_PROJECT_ID}/census31-eq-questionnaire-launcher/launcher:${SHORT_SHA}"

substitutions:
  _PLATFORM: "linux/amd64"

options:
  logging: CLOUD_LOGGING_ONLY
