---
steps:
  - id: docker-build-eq-launcher
    name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - "--platform=${_PLATFORM}"
      - "--load"
      - "-t"
      - "europe-west2-docker.pkg.dev/${_PROJECT_ID}/images/census31-eq-questionnaire-launcher:${SHORT_SHA}"
      - "."

  - id: docker-tag-latest
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - "europe-west2-docker.pkg.dev/${_PROJECT_ID}/images/census31-eq-questionnaire-launcher:${SHORT_SHA}"
      - "europe-west2-docker.pkg.dev/${_PROJECT_ID}/images/census31-eq-questionnaire-launcher:latest"

images:
  - "europe-west2-docker.pkg.dev/${_PROJECT_ID}/images/census31-eq-questionnaire-launcher:${SHORT_SHA}"
  - "europe-west2-docker.pkg.dev/${_PROJECT_ID}/images/census31-eq-questionnaire-launcher:latest"

substitutions:
  _PLATFORM: "linux/amd64"

options:
  logging: CLOUD_LOGGING_ONLY
