steps:  
  # Build Docker image
  - name: gcr.io/cloud-builders/docker
    id: docker-build
    args:
      - build
      - "-t"
      - "europe-west2-docker.pkg.dev/$PROJECT_ID/census31-eq-questionnaire-launcher/validator:$SHORT_SHA"
      - .

  # Push Docker image to GAR
  - name: gcr.io/cloud-builders/docker
    id: docker-push
    args:
      - push
      - "europe-west2-docker.pkg.dev/$PROJECT_ID/census31-eq-questionnaire-launcher/launcher:$SHORT_SHA"

images:
  - "europe-west2-docker.pkg.dev/$PROJECT_ID/census31-eq-questionnaire-launcher/launcher:$SHORT_SHA"

substitutions:
  _ICON_EMOJI: ":cicd:"
  _SLACK_PUBLISHER_SERVICE_ACCOUNT: "$_SLACK_PUBLISHER_SERVICE_ACCOUNT"
  _TRIGGER_NAME: "$_TRIGGER_NAME"

options:
  logging: CLOUD_LOGGING_ONLY
