---
steps:
  - id: docker-build-eq-launcher
    name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - "--platform=${_PLATFORM}"
      - "--load"
      - "-t"
      - "launcher-pr:${SHORT_SHA}"
      - "."

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PLATFORM: "linux/amd64"
